name: Update Task Progress

on:
  issues:
    types: [edited]

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug environment
        run: |
          echo "Checking GH_TOKEN environment variable..."
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "Error: GH_TOKEN is not set."
            exit 1
          else
            echo "GH_TOKEN is set correctly."
          fi

      - name: Calculate task progress
        id: calculate-progress
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Extract the issue body
          ISSUE_BODY=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} --jq '.body')
          # Debug log for the issue body
          echo "Issue Body: $ISSUE_BODY"

          # Count total tasks (checkboxes) and completed tasks
          TOTAL_TASKS=$(echo "$ISSUE_BODY" | grep -oE '\- \[[ x]\]' | wc -l)
          COMPLETED_TASKS=$(echo "$ISSUE_BODY" | grep -oE '\- \[x\]' | wc -l)

          # Debug log for task counts
          echo "Total tasks: $TOTAL_TASKS"
          echo "Completed tasks: $COMPLETED_TASKS"

          # Handle no tasks case
          if [ "$TOTAL_TASKS" -eq 0 ]; then
            echo "No tasks found."
            echo "progress=0" >> $GITHUB_ENV
            exit 0
          fi

          # Calculate progress percentage
          PROGRESS=$(( COMPLETED_TASKS * 100 / TOTAL_TASKS ))
          echo "Progress: $PROGRESS%"
          echo "progress=$PROGRESS" >> $GITHUB_ENV

      - name: Update the issue with progress
        if: env.progress != '' # No 'env' block needed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PROGRESS="${{ env.progress }}"
          # Fetch the existing issue title
          CURRENT_TITLE=$(gh api repos/${{github.repository }}/issues/${{github.event.issue.number }} --jq '.title')
          echo "Current Title: $CURRENT_TITLE"

          # Remove any previous progress info from the title
          CLEANED_TITLE=$(echo "$CURRENT_TITLE" | sed -E 's/\[[0-9]+\/[0-9]+ %\]//g' | sed 's/ *$//')

          # Append progress as [x/y Tasks] to the title
          UPDATED_TITLE="$CLEANED_TITLE [$COMPLETED_TASKS/$TOTAL_TASKS %]"
          echo "Updated Title: $UPDATED_TITLE"

          # Update the issue title
          gh api repos/${{github.repository }}/issues/${{ github.event.issue.number }} \
            --method PATCH \
            --field title="$UPDATED_TITLE"
