name: Update Task Progress

on:
  issues:
    types: [edited]

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug environment
        run: |
          echo "Checking GH_TOKEN environment variable..."
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "Error: GH_TOKEN is not set."
            exit 1
          else
            echo "GH_TOKEN is set correctly."
          fi

      - name: Calculate task progress
        id: calculate-progress
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Extract the issue body
          ISSUE_BODY=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} --jq '.body')
          echo "Issue Body: $ISSUE_BODY"

          # Count tasks
          TOTAL_TASKS=$(echo "$ISSUE_BODY" | grep -oE '\[.\]' | wc -l)
          COMPLETED_TASKS=$(echo "$ISSUE_BODY" | grep -oE '\[x\]' | wc -l)

          # Debug logs
          echo "Total tasks: $TOTAL_TASKS"
          echo "Completed tasks: $COMPLETED_TASKS"

          # Handle no tasks
          if [ "$TOTAL_TASKS" -eq 0 ]; then
            echo "No tasks found."
            echo "progress=0" >> $GITHUB_ENV
            echo "completed=0" >> $GITHUB_ENV
            echo "total=0" >> $GITHUB_ENV
            exit 0
          fi

          # Calculate progress
          PROGRESS=$(( COMPLETED_TASKS * 100 / TOTAL_TASKS ))
          echo "Progress: $PROGRESS%"
          echo "progress=$PROGRESS" >> $GITHUB_ENV
          echo "completed=$COMPLETED_TASKS" >> $GITHUB_ENV
          echo "total=$TOTAL_TASKS" >> $GITHUB_ENV

      - name: Update the issue title with progress
        if: env.progress != ''
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Use calculated progress and task counts
          PROGRESS="${{ env.progress }}"
                 
          # Fetch current labels as an array of names
          CURRENT_LABELS=$(gh api repos/${{github.repository }}/issues/${{github.event.issue.number }} --jq '[.labels[].name]')
          echo "Current Labels: $CURRENT_LABELS"

          # Remove old progress labels, if any
          FILTERED_LABELS=$(echo "$CURRENT_LABELS" | jq '[.[] | select(test("^Progress: [0-9]+%") | not)]')
          echo "Filtered Labels: $FILTERED_LABELS"

          # Add the new progress label
          UPDATED_LABELS=$(echo "$FILTERED_LABELS" | jq ". += [\"Progress: $PROGRESS%\"]")
          echo "Updated Labels JSON: $UPDATED_LABELS"

          # Extract each label as a --field argument
          FIELDS=""
          for label in $(echo "$UPDATED_LABELS" | jq -r '.[]'); do
            FIELDS+="--field labels[]=\"$label\" "
          done

          # Debug fields
          echo "Final Label Fields: $FIELDS"

          # Update the labels using GitHub API
          eval gh api repos/${{github.repository }}/issues/${{github.event.issue.number }} \
            --method PATCH \
            $FIELDS
   
