name: Update Task Progress

on:
  issues:
    types: [edited]

jobs:
  update-progress:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug environment
        run: |
          echo "Checking GH_TOKEN environment variable..."
          if [ -z "${{ secrets.GH_TOKEN }}" ]; then
            echo "Error: GH_TOKEN is not set."
            exit 1
          else
            echo "GH_TOKEN is set correctly."
          fi

      - name: Calculate task progress
        id: calculate-progress
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          # Extract the issue body
          ISSUE_BODY=$(gh api repos/${{ github.repository }}/issues/${{ github.event.issue.number }} --jq '.body')
          echo "Issue Body: $ISSUE_BODY"

          # Count tasks
          TOTAL_TASKS=$(echo "$ISSUE_BODY" | grep -oE '\[.\]' | wc -l)
          COMPLETED_TASKS=$(echo "$ISSUE_BODY" | grep -oE '\[x\]' | wc -l)

          # Debug logs
          echo "Total tasks: $TOTAL_TASKS"
          echo "Completed tasks: $COMPLETED_TASKS"

          # Handle no tasks
          if [ "$TOTAL_TASKS" -eq 0 ]; then
            echo "No tasks found."
            echo "progress=0" >> $GITHUB_ENV
            echo "completed=0" >> $GITHUB_ENV
            echo "total=0" >> $GITHUB_ENV
            exit 0
          fi

          # Calculate progress
          PROGRESS=$(( COMPLETED_TASKS * 100 / TOTAL_TASKS ))
          echo "Progress: $PROGRESS%"
          echo "progress=$PROGRESS" >> $GITHUB_ENV
          echo "completed=$COMPLETED_TASKS" >> $GITHUB_ENV
          echo "total=$TOTAL_TASKS" >> $GITHUB_ENV

      - name: Update the issue with progress
        if: env.progress != '' # No 'env' block needed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          PROGRESS="${{ env.progress }}"
          # Fetch the existing issue title
          CURRENT_TITLE=$(gh api repos/${{github.repository }}/issues/${{github.event.issue.number }} --jq '.title')
          echo "Current Title: $CURRENT_TITLE"

          # Remove any previous progress info from the title
          CLEANED_TITLE=$(echo "$CURRENT_TITLE" | sed -E 's/\[[^]]+\]//g' | sed 's/ *$//')

          # Create a progress bar (10 segments for 100%)
          BAR_LENGTH=10
          FILLED_BLOCKS=$(( (PROGRESS * BAR_LENGTH) / 100 ))
          EMPTY_BLOCKS=$(( BAR_LENGTH - FILLED_BLOCKS ))
          PROGRESS_BAR=$(printf '%*s' $FILLED_BLOCKS | tr ' ' '█')$(printf '%*s' $EMPTY_BLOCKS | tr ' ' '░')

          # Append progress bar with percentage
          UPDATED_TITLE="$CLEANED_TITLE [$PROGRESS_BAR] ($PROGRESS%)"
          echo "Updated Title: $UPDATED_TITLE"

          # Update the issue title
          gh api repos/${{github.repository }}/issues/${{ github.event.issue.number }} \
            --method PATCH \
            --field title="$UPDATED_TITLE"
